config/routes.rb
FbUserChecker::Application.routes.draw do
  root 'profiles#index'

  resources :profiles, only:[:index,:create,:update, :show] do
    collection do
      get 'test_index'      
      post 'update_test'
      get 'destoy_unmarked'
      post 'retest_each'
    end
    post 'test', on: :member
  end

  resources :posts, only:[:index, :create, :destroy] do
    member do
      post 'manual_type'
      get 'likers'
      post 'add_likers'
    end
    
    post 'recalc_rate_all', on: :collection    
  end

end

app/models/post.rb
class Post < ActiveRecord::Base  
  has_and_belongs_to_many  :profiles, :uniq => true

  scope :promo, -> {where("rate >= 1")}
  scope :usual, -> {where("rate < 1 ")}

  scope :auto, -> {where('manual_check IS NULL')}
  scope :manual, -> {where('manual_check IS NOT NULL')}

  validates :text, :uniqueness => true
  before_save :check_link_lenght, :check_rate

  def fetch (fb_post=nil)
    fb_post ||= FbGraph::Post.fetch(self.pid,:access_token => Profile.token)
    self.text = fb_post.name || fb_post.caption || fb_post.description || fb_post.message
    self.link = fb_post.link    
  end

  def fetch!
    self.fetch
    self.save
  end

  def recalc_rate!
    stemmer= Lingua::Stemmer.new(language: "ru")
    self.fetch! unless self.text
    clean_text = self.text.gsub(/[^a-zA-Zа-яА-Я’їієґЇІЄҐ]/,' ')
    clean_text = UnicodeUtils.downcase( clean_text ) 
    words = clean_text.split(' ')
    words.map!{|word| stemmer.stem(word)}
    words = words.to_set
    self.rate = 0
    TestConstants.bad_words.each do |black_word,val|
      self.rate+=val if words.include? black_word
    end   

    if self.promo? == self.manual_check
      self.manual_check = nil # algorithm become better!
    end

    self.save
    return self.rate
  end

  def promo?
    self.rate >= 1
  end

  def self.create_or_find_same_from_fb_post fb_post
    
    if fb_post.graph_object_id && fb_post.raw_attributes['status_type'] == "shared_story"
      begin
        fb_post = FbGraph::Post.fetch(fb_post.graph_object_id,:access_token => Profile.token)
      rescue => e
        #cant find original
      end
    end

    post = Post.new(pid: fb_post.identifier)
    post.fetch fb_post
    
    if(post.text)
      same_post = Post.where(text: post.text).first
      if same_post
        post = same_post 
      else
        post.save
      end
      return post
    else
      return nil
    end

  end

  def self.manual_percent
    per = self.manual.count.to_f / self.all.count.to_f
    per = (per*100).round(1)
  end

  def self.donwload_from_fb id, limit
    object = FbGraph::User.fetch(id, access_token: Profile.token)
    fb_posts = object.posts(limit: limit)
    fb_posts.each do |fb_post|
      self.create_or_find_same_from_fb_post(fb_post)
    end    
  end

  def fb_object
    FbGraph::Post.fetch(self.pid,:access_token => Profile.token)
  end

  def upload_likers count, fb_post=nil
    fb_post ||= self.fb_object
    
    if fb_post.graph_object_id
      begin
        fb_post = FbGraph::Post.fetch(fb_post.graph_object_id,:access_token => Profile.token)
      rescue => e
        
      end
    end
    
    likers = fb_post.likes(limit:count.to_i)
    likers.each do |fb_user|
      p = Profile.create_from_fb(fb_user)
      p.posts<<self      
    end
  end

  def promo_likers
    self.profiles.promo_hunters
  end

  private
  def check_link_lenght    
    self.link = self.link.first(255) if self.link?
  end

  def check_rate
    self.recalc_rate! if self.rate.nil?
  end  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_and_belongs_to_many :posts, :uniq => true

  validates :uid, :uniqueness => true
  scope :tested, -> {where.not(ph_percent:nil)}
  scope :checked, -> {where.not(ph_manual:nil)}
  scope :promo_hunters, -> {where('ph_percent >= ?',TestConstants.ph_post_percent)}

  def link
    "https://www.facebook.com/profile.php?id="+self.uid
  end

  def self.token
    'CAAUgLojNQaoBAFSh9rs7snOhvuTCGQAWJzijIYQdw8MsBLpcbXCFQZCB5daBAxW3I1j4YZCZBI7Vjsnm20ztG3LP2iWBJHfhC1vCmXjRcbEHd657u1VFOqYiOnWpfZBa6MaZBjVPw0ZCb8BsSwBo5u9CXrI8UStqRidZCky64HMStZB737DgmrkG9UKV4tnJsI8ZD'
  end  

  def retest!    
    user_object = FbGraph::User.fetch(self.uid, :access_token => Profile.token)

    posts = user_object.posts  

    Post.transaction do 
      posts.each do |fb_post|      
          post = Post.create_or_find_same_from_fb_post( fb_post )
          self.posts<<post if post      
      end
    end

    bad_post_counter = self.posts.auto.promo.count
    if self.posts.any?
      self.ph_percent = bad_post_counter.to_f / self.posts.size.to_f
    else
      self.ph_percent = 0;
    end

    promo_hunter = (self.ph_percent>= TestConstants.ph_post_percent)
    self.right = (promo_hunter == self.ph_manual ) if self.ph_manual
    self.save
  end

  def type
    (self.ph_percent||=0) >= TestConstants.ph_post_percent ? "Призолов" : "Обычный"
  end

  def self.create_from_fb fb_user
    Profile.create(uid: fb_user.identifier, name:fb_user.name)
  end

  def self.right_percent
    per = Profile.checked.where(right:true).count.to_f/Profile.checked.count.to_f
    per = (per*100).round(1)
  end

  def color
    if self.right
      'green'
    else
      if self.right.nil?
        'grey'
      else
        'red'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    posts = params[:manual] ? Post.manual : Post.auto        
    @promo_posts = posts.promo.order("rate ")
    @usual_posts = posts.usual.order("rate DESC")    
  end

  def manual_type
    post = Post.find(params[:id])
    post.update(manual_check: params[:type])
    post.save
    respond_to do |format|
      format.html { redirect_to action: 'index' }
      format.js {render nothing: true}
    end
    
  end

  def recalc_rate_all
    Post.all.each(&:recalc_rate!)
    redirect_to action: 'index'
  end

  def create
    Post.donwload_from_fb(params[:id], params[:limit])
    redirect_to action: 'index'
  end

  def likers
    @post = Post.find(params[:id])
    @profiles = @post.profiles.order(:created_at)    
  end

  def add_likers
    @post = Post.find(params[:id])
    @post.upload_likers(params[:count].to_i)
    redirect_to action: 'likers'
  end

  def destroy
    Post.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to :back  }
      format.js {render nothing: true}
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all.order(:created_at)
  end

  def show
    @profile = Profile.find(params[:id])
    @profile.retest! if params[:retest]
    @promo_posts = @profile.posts.promo
    @usual_posts = @profile.posts.usual
  end

  def create    
    fb_post = FbGraph::Post.fetch(params[:post_id],:access_token => Profile.token)    
    post = Post.create_or_find_same_from_fb_post fb_post
    post.upload_likers(params[:limit].to_i, fb_post)
    redirect_to profiles_path
  end  

  def update
    profile = Profile.find(params[:id])
    profile_params = params.require(:profile).permit(:ph_manual)
    profile_params[:ph_manual] = nil if profile_params[:ph_manual]=='on'
    profile.update(profile_params)
    profile.save
    respond_to do |format|
      format.html { redirect_to action: 'index' }
      format.js {render nothing: true}
    end
  end

  def test_index
    @profiles = Profile.order(:created_at)
    @bw = TestConstants.bad_words
    @ph_post_percent = TestConstants.ph_post_percent
  end

  def test
    profile = Profile.find(params[:id])
    profile.retest!
    render json: {percent:profile.ph_percent, right:profile.right, color: profile.color, type: profile.type}
  end

  def update_test
    TestConstants.ph_post_percent = params[:ph_post_percent].to_f
    bw = params[:bw].each{|k,v| params[:bw][k] = v.to_f}
    TestConstants.bad_words = bw
    redirect_to test_index_profiles_path
  end

  def destoy_unmarked    
    Profile.where(ph_manual:nil).destroy_all
    redirect_to profiles_path
  end

  def retest_each
    Profile.checked.each(&:retest!)
    redirect_to test_index_profiles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FbUserChecker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Профили', profiles_path %>
<%= link_to 'Тестирование', test_index_profiles_path %>
<%= link_to 'Посты', posts_path %>
<%= Post.manual_percent %>%
<hr>

<%= yield %>

</body>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</html>

app/views/posts/_post.html.haml
.post
  .destroy.inline_button
    = button_to 'Удалить', post_path(post), method: :delete , confirmation: 'Точно удалиить?', remote: true
  |
  = link_to 'Лайкующие', likers_post_path(post) 
  |
  = link_to 'Оригинал', post.link if post.link 
  |  
  = post.rate  
  .manual_type.inline_button
    - if post.manual_check.nil?
      = button_to 'Не верно', manual_type_post_path( post, type: !post.promo? ), remote: true
    - else
      = button_to 'Ой, верните', manual_type_post_path( post, type: nil ), remote: true
  .original
    = post.text
  %hr

app/views/posts/index.html.haml
=form_for Post.new do |f|
  = text_field_tag :id, 'dolcegustoua', placeholder: 'id'
  = text_field_tag :limit, 20
  = f.submit
%hr
.inline_button
  = button_to 'Перетестировать', recalc_rate_all_posts_path
- if params[:manual]
  =link_to "Авто", posts_path 
-else
  =link_to "Не верные!", posts_path(manual:true)
%hr
%table.posts
  %tr
    %td
      - @promo_posts.each do |post|
        = render post        
        
    %td
      - @usual_posts.each do |post|
        = render post        
        

app/views/posts/likers.html.haml
.post
  = render @post
.stat
  = @post.profiles.promo_hunters.count 
  = "/"
  = @post.profiles.tested.count
%hr
= form_tag add_likers_post_path(@post) do 
  = label_tag :count, 'Количество'
  = text_field_tag :count  
  = submit_tag 'Добавить еще'
%hr
= label_tag :auto_click, 'Авто клик'
= check_box_tag :auto_click, false
%table.profiles  
  - @profiles.each do |profile|
    %tr
      = render profile
      = render partial:'profiles/form', locals:{profile: profile}

app/views/profiles/_form.html.haml
%td.profile_form
  = form_for profile, remote: true do |f|
    = f.label :ph_manual, "Призолов", :value => "true"
    = f.radio_button :ph_manual, true
    = f.label :ph_manual, "Нормальный", :value => "false"
    = f.radio_button :ph_manual, false
    = f.label :ph_manual, "?", :value => nil
    = f.radio_button :ph_manual, nil

app/views/profiles/_profile.html.haml
-if profile.ph_manual
  %td.ph
    !
- else
  %td.ok                
%td.profile_name     
  =link_to profile.name, profile.link
%td.profile_button
  =button_to 'Проверить',test_profile_path(profile), :remote=>true, class: 'check_one'
%td.percentage
  =text_field_tag 'per', profile.ph_percent, style:"background-color:#{profile.color}"
%td.type
  = link_to profile.type, profile_path(profile)

app/views/profiles/index.html.haml
=form_for Profile.new do |f|
  = text_field_tag :post_id, 526085694165129, placeholder: 'id Поста'
  = text_field_tag :limit, 20
  = f.submit
%hr
= link_to 'Удалить все непроверенные', destoy_unmarked_profiles_path
%hr
%table
  - @profiles.each do |profile|
    %tr
      %td.profile_name      
        =link_to profile.name, profile.link
      = render partial:'form', locals:{profile:profile}

app/views/profiles/show.html.haml
=link_to @profile.name, @profile.link
= link_to 'Обновить', profile_path(@profile, retest: true)
%table.posts
  %tr
    %td
      %h3
        Призоловские
    %td
      %h3
        Обычные
  %tr
    %td
      - @promo_posts.each do |post|
        = render partial: 'posts/post', :locals => { post: post } # change to render :post ?
    %td
      - @usual_posts.each do |post|
        = render partial: 'posts/post', :locals => { post: post }

app/views/profiles/test_index.html.haml
.form_wrapper
  =form_tag update_test_profiles_path(),remote:true do 
    = label_tag 'Процент призолова'
    %br
    = text_field_tag :ph_post_percent, @ph_post_percent
    %hr
    - @bw.each do |key,val|
      .bw
        = text_field_tag 'bw['+key+']',val,class:'bw_val'
        = label_tag 'bw['+key+']',key
    %hr
    = button_tag 'Обновить константы', disabled:true
= label_tag :auto_click, 'Авто клик'
= check_box_tag :auto_click, false
//= button_to 'Обновить все', retest_each_profiles_path
%table.profiles  
  - @profiles.each do |profile|
    %tr
      = render profile